import { Inter } from 'next/font/google';
import './card.scss';
import Navbar from './components/navbar';
import './globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen mx-5 md:mx-8 lg:mx-12 xl:mx-16 2xl:mx-24">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  )
}
