export const skillsImage = (skill) => {
  const skillMap = {
    HTML: "/svg/skills/html.svg",
    CSS: "/svg/skills/css.svg",
    Javascript: "/svg/skills/javascript.svg",
    Typescript: "/svg/skills/typescript.svg",
    React: "/svg/skills/react.svg",
    "Next JS": "/svg/skills/nextJS.svg",
    Tailwind: "/svg/skills/tailwind.svg",
    MongoDB: "/svg/skills/mongoDB.svg",
    PostgreSQL: "/svg/skills/postgresql.svg",
    Git: "/svg/skills/git.svg",
    Bootstrap: "/svg/skills/bootstrap.svg",
    Figma: "/svg/skills/figma.svg",
    Firebase: "/svg/skills/firebase.svg",
    MaterialUI: "/svg/skills/materialui.svg",
    "Node JS": "/svg/skills/nodejs.svg",
    Vue: "/svg/skills/vue.svg",
    Angular: "/svg/skills/angular.svg",
    Docker: "/svg/skills/docker.svg",
    Python: "/svg/skills/python.svg",
    Java: "/svg/skills/java.svg",
    PHP: "/svg/skills/php.svg",
    AWS: "/svg/skills/aws.svg",
    MySQL: "/svg/skills/mysql.svg",
    Prisma: "/svg/skills/prisma.svg",
    ViteJS: "/svg/skills/vitejs.svg",
    "Nuxt JS": "/svg/skills/nuxtJS.svg",
    Svelte: "/svg/skills/svelte.svg",
    Flutter: "/svg/skills/flutter.svg",
    Dart: "/svg/skills/dart.svg",
    Go: "/svg/skills/go.svg",
    C: "/svg/skills/c.svg",
    "C++": "/svg/skills/cplusplus.svg",
    "C#": "/svg/skills/csharp.svg",
    Swift: "/svg/skills/swift.svg",
    Kotlin: "/svg/skills/kotlin.svg",
    Ruby: "/svg/skills/ruby.svg",
    Julia: "/svg/skills/julia.svg",
    Matlab: "/svg/skills/matlab.svg",
    Deno: "/svg/skills/deno.svg",
    Django: "/svg/skills/django.svg",
    FastAPI: "/svg/skills/fastapi.svg",
    GraphQL: "/svg/skills/graphql.svg",
    Nginx: "/svg/skills/nginx.svg",
    Strapi: "/svg/skills/strapi.svg",
    Wordpress: "/svg/skills/wordpress.svg",
    Unity: "/svg/skills/unity.svg",
    Blender: "/svg/skills/blender.svg",
    Photoshop: "/svg/skills/photoshop.svg",
    Illustrator: "/svg/skills/illustrator.svg",
    "Adobe XD": "/svg/skills/adobe-xd.svg",
    "After Effects": "/svg/skills/after-effects.svg",
    "Premiere Pro": "/svg/skills/premierepro.svg",
    "Adobe Audition": "/svg/skills/adobeaudition.svg",
    Canva: "/svg/skills/canva.svg",
    Sketch: "/svg/skills/sketch.svg",
    Gimp: "/svg/skills/gimp.svg",
    Lightroom: "/svg/skills/lightroom.svg",
    Picsart: "/svg/skills/picsart.svg",
    "Microsoft Office": "/svg/skills/microsoftoffice.svg",
    Markdown: "/svg/skills/markdown.svg",
    Linux: "/svg/skills/linux.svg",
    Ubuntu: "/svg/skills/ubuntu.svg",
    Azure: "/svg/skills/azure.svg",
    GCP: "/svg/skills/gcp.svg",
    Kubernetes: "/svg/skills/kubernetes.svg",
    CapacitorJs: "/svg/skills/capacitorjs.svg",
    Ionic: "/svg/skills/ionic.svg",
    Bulma: "/svg/skills/bulma.svg",
    VuetifyJS: "/svg/skills/vuetifyjs.svg",
    Webix: "/svg/skills/webix.svg",
    WolframAlpha: "/svg/skills/wolframalpha.svg",
    Numpy: "/svg/skills/numpy.svg",
    Pandas: "/svg/skills/pandas.svg",
    OpenCV: "/svg/skills/opencv.svg",
    Pytorch: "/svg/skills/pytorch.svg",
    Tensorflow: "/svg/skills/tensorflow.svg",
    "Scikit-learn": "/svg/skills/scikit-learn.svg",
    Selenium: "/svg/skills/selenium.svg",
    SQLAlchemy: "/svg/skills/sqlalchemy.svg",
    SQLite: "/svg/skills/sqlite.svg",
    MemSQL: "/svg/skills/memsql.svg",
    Coffeescript: "/svg/skills/coffeescript.svg",
    Haxe: "/svg/skills/haxe.svg",
    Fastify: "/svg/skills/fastify.svg",
    Dotnet: "/svg/skills/dotnet.svg",
    Dotnetcore: "/svg/skills/dotnetcore.svg",
    Webex: "/svg/skills/webex.svg",
  };

  const imagePath = skillMap[skill];
  if (imagePath) {
    return { src: imagePath };
  }

  // Return null instead of empty string to prevent the warning
  return null;
};
